version: "3.8"

services:
  CodeCompiler:
    image: postgres:latest
    restart: no
    container_name: CodeCompiler
    volumes:
      - volumename:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=CodeCompiler
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: no
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  volumename:
  redisdata:
